title: Motivational Daily
email: motivational@senpaidev.com
description: > # this means to ignore newlines until "baseurl:"
  Get daily motivational quotes. Download the app from the App Store today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://motivational.senpaidev.com" # the base hostname & protocol for your site
twitter_username: senpaidevlabs
github_username:  senpaidevlabs

# Build settings
markdown: kramdown

permalink: /quote/:year/:month/:day.html
